# docker compose yml としての書き方の バージョン
version: '3.8'

# 立てるコンテナ一覧
services:
  # アプリケーション
  app:
    # 管理コンテナ名
    container_name: ${APP_NAME}-app
    # Dockerファイルにて 定義
    build: ./docker/php
    # 場所
    volumes:
      - ./laravel-src/:/var/www/html
    # 利用ポート
    ports:
      # 一旦 フロントエンド vite使う感じで
      - ${VITE_PORT:-5173}:5173
    # 環境設定値設定
    environment:
      # アプリ系
      - APP_NAME=${APP_NAME}
      - APP_URL=${APP_URL:-http://localhost:8080}
      - APP_ENV=${APP_ENV:-local}
      # DB 接続定義
      - DB_CONNECTION=${DB_CONNECTION:-pgsql}
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_DATABASE=${DB_DATABASE:-sample_db}
      - DB_USERNAME=${DB_USERNAME:-manager}
      - DB_PASSWORD=${DB_PASSWORD:-zaq12wsx}
  # メインアプリ WEBサーバー
  web:
    # 管理コンテナ名
    container_name: ${APP_NAME}-web
    # Dockerファイルにて 定義
    build: ./docker/nginx
    # 利用ポート
    ports:
      - ${WEB_PORT:-8080}:80
    # 依存関係
    depends_on:
      - app
    # 場所
    volumes:
      - ./laravel-src/:/var/www/html
    # 環境設定値
    environment:
      # nginx 対応 ホスト名(一旦コンテナごと)
      - PHP_APP_HOST=app
    # コマンド
    # defaut.conf内容書き換え
    command: /bin/sh -c "envsubst '$$PHP_APP_HOST' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  # db
  db:
    # 管理コンテナ名
    container_name: ${APP_NAME}-db
    # Dockerファイルにて 定義
    build: ./docker/postgres
    # ホスト名指定
    hostname: ${DB_HOST:-postgres}
    # 利用ポート
    ports:
      - ${DB_PORT:-5432}:5432
    # postgreSQL へのオプション (PGDATA: データベースの物理的な格納場所の指定 POSTGRES_INITDB_ARGS起動引数)
    environment:
      POSTGRES_USER: ${DB_USERNAME:-manager}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-zaq12wsx}
      POSTGRES_DB: ${DB_DATABASE:-sample_db}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    # データ保存場所やログ残す場所:postgresシステムとしてのパス (/var/lib/postgresql/data) (ショートカットリンク先のパス:ショートカットリンクパス)
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./db/logs:/var/log
